spring:
  jpa:
    hibernate:
      show-sql: false
      format-sql: true
      physical-strategy: org.example.persistence.config.SnakeCasePhysicalNamingStrategy

logging:
  level:
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  observations:
    key-values:
      application: ${spring.application.name:gym-management-system}