spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/test_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  activemq:
    broker-url: tcp://localhost:61616

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

jwt:
  secret: myVerySecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmToWork
  expiration: 86400000

logging:
  level:
    org.hibernate: INFO
    org.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true